maintainer: Dhanoop Karunakaran
debug: True
dir: 'pdfs'
GOOGLE_API:
  no_emails: 50
  subjects:
    - 'FDC Invoice Dev'
    - 'Your Energy Locals Urban Invoice'
    - 'Sydney Water eBill'
    - 'Uniti Retail Pty Ltd - Invoice' # it has attachment, but email body contains info clear
    - 'Telstra Upfront Mobile Plan'
    - 'Strata Plan100063 91 GRIMA STREET'
  # Each subject should have a payment method
  payment_methods:
    - 'Manual'
    - 'Direct Debit'
    - 'Bpay'
    - 'Manual'
    - 'Credit Card'
    - 'Bpay'
  # Each subject should have a download method
  download_methods:
    - 'attachment'
    - 'attachment'
    - 'email_body'
    - 'email_body' 
    - 'google_drive_file'
    - 'attachment'
  senders:
    - 'mariaka1@me.com'
    - 'dhanooponline@gmail.com'
    - 'sender@sydneywater.com.au'
    - 'support@unitiinternet.com'
    - 'google_drive_file'
    - 'notices@netstrata.com.au'
  scopes:
    - 'https://www.googleapis.com/auth/gmail.readonly'
    - 'https://www.googleapis.com/auth/tasks'
    - 'https://www.googleapis.com/auth/drive'
  no_of_drive_files: 20
  drive_folder_name: 'track_my_bill_content'
ollama:
  host: 'http://192.168.0.160:11434' #'http://127.0.0.1:11434'
  model: 'llama-3.2-3B-instruct-q8-invoice:latest' #'llama3.1:8b'
  template: "
        Your task is to extract invoice data from the text '{context}'.

        Reply Structures:
        - Amount 
        - Due_date 
        - Biller_name   

        Reply with valid json. Please make sure Due_date is in year-month-day format and Biller_name has only a few words
      "
sql_alchemy:
  loc: '/app/data'
  db: 'data.db'
invoice_agent:
  host: 'http://192.168.0.160:11434' #'http://127.0.0.1:11434'
  model_for_API_tool: 'qwen2:7b-instruct-q8_0'
  prompt_for_API_tools: "Assistant is a large language model trained by Meta.

    Assistant is designed to be able to assist with a wide range of tasks, from answering 
    simple questions to providing in-depth explanations and discussions on a wide range of 
    topics. As a language model, Assistant is able to generate human-like text based on the input it receives, allowing it to engage in natural-sounding conversations and provide responses that are coherent and relevant to the topic at hand.

    Assistant doesn't know anything about random numbers or anything related to the meaning
    of life and should use a tool for questions about these topics.

    Assistant is constantly learning and improving, and its capabilities are constantly 
    evolving. It is able to process and understand large amounts of text, and can use 
    this knowledge to provide accurate and informative responses to a wide range of 
    questions. Additionally, Assistant is able to generate its own text based on the 
    input it receives, allowing it to engage in discussions and provide explanations and 
    descriptions on a wide range of topics.

    Overall, Assistant is a powerful system that can help with a wide range of tasks and 
    provide valuable insights and information on a wide range of topics. Whether you need 
    help with a specific question or just want to have a conversation about a particular 
    topic, Assistant is here to assist."