maintainer: Dhanoop Karunakaran
debug: False
gmail:
  no_emails: 10
  subjects:
    - 'FDC Invoice Dev'
    - 'FDC Receipt Dev'
    - 'Your Energy Locals Urban Invoice'
  senders:
    - 'mariaka1@me.com'
    - 'dhanooponline@gmail.com'
  scopes:
    - 'https://www.googleapis.com/auth/gmail.readonly'
ollama:
  host: 'http://192.168.0.160:11434'
  model: 'llama3.1:8b'
  template: '
        You are expert in finding the entities from the test and extract relevant information and return only the JSON with the following content. 
        Find the amount to be paid, due date, and get the biller name(just the name only) in the following formats:
        Amount: 
        Due_date: 
        Biller_name:

        Here is the text for extracting the information: {context}.

      '