# Ref 1 - https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/?source=post_page-----ac33851d573d--------------------------------
# Ref 2 - https://medium.com/@pandit.summit/kubernetes-cron-job-with-python-image-in-minikube-windows-10-ac33851d573d
# pods=$(kubectl get pods --selector=job-name=track-my-bills-28896504 --output=jsonpath={.items[*].metadata.name})
apiVersion: batch/v1
kind: CronJob
metadata:
  name: track-my-bills-cron
spec:
  schedule: "0 11 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: track-my-bills # Container name for reference
            image: track_my_bills
            imagePullPolicy: IfNotPresent
            command: ["python", "main.py"]
          restartPolicy: OnFailure
